
services:
  app_vet:
    build:
      context: ./clinicaVet  # Apunta a la carpeta que contiene el Dockerfile
      dockerfile: DockerFile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment: 
      DB_URL: jdbc:mysql://clinica_vet:3306/clinica_veterinaria?createDatabasesIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 123456
    restart: always
    depends_on:
      clinica_vet:
        condition: service_healthy
  clinica_vet:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: clinica_veterinaria
    restart: always
    #chequeo de salud(si esta levantado)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping" , "-h", "localhost"]
      timeout: 10s
      retries: 10
      
       